### ISSUE TITLE
 color/size legend  

### ISSUE THREAD

**Issue by chapinux** [Universite-Gustave-Eiffel/lasso#19]
what :  a legend item displayed whenever a variable is mapped on color or size attribute
where : 
    -  in the select layer drop-down menu
    - in between the two maps 
    - below the focus/autoscale button 

Ideally : The display of the legend could be disabled at will

**Comment by pierromond** [comment]
- in the select layer drop-down menu

**Comment by sim51** [comment]
![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/ae079a65-6df3-4d1d-b441-cf5a7127f0f0)
