### ISSUE TITLE
Transfer property

### ISSUE THREAD

**Issue by pierromond** [Universite-Gustave-Eiffel/lasso#20]
A priori, c'est plutôt de votre côté que ça se passe. Le transfert de propriété doit se faire vers : https://github.com/Universite-Gustave-Eiffel/LASSO 

Je n'ai pas encore créé de dépôt, n'hésitez pas à me dire si c'est nécessaire, ou ce dont vous avez besoin !

A suivre :)

**Comment by sim51** [comment]
Vu qu'on a pas les droits dans l'orga cible de créer un nouveau repo, on peut pas faire le transfert.
Alors on t'a ajouté en tant qu'admin du projet pour que tu puisses faire le transfert.

**Comment by pierromond** [comment]
C'est bon :) C'est réussi !
