### ISSUE TITLE
Add dataset tab

### ISSUE THREAD

**Issue by pierromond** [Universite-Gustave-Eiffel/lasso#21]
- to describe the dataset and its layers
- add a link to this tab in the info popup

**Comment by pierromond** [comment]
- just add dataset tab
- maybe read hmtl injection interpretation

**Comment by pierromond** [comment]
see commit aad44cf

**Comment by sim51** [comment]
@pierromond  Following your commit, is there something else to do ?

**Comment by pierromond** [comment]
mmmm maybe just check that I didn't do a mistake :) haha and deploy this new "dataset tab" in the template and the other datasets

**Comment by sim51** [comment]
I checked the code,  and everything is good ! 
About the  deploy part, it's up to you to add this markdown file in projects.

There is one remaining task which is "add a link to this tab in the info popup" but I don't of which info popup you talk about. Can give me some intel ?

Thanks

**Comment by pierromond** [comment]
I think we spoke one time about a popup with info (explaining the interface*) when we open the dataset, but I am not sure we created this issue, maybe you will find it. Otherwise, that's not so important.

* In the spirit of this popup but much shorter.

**Comment by pierromond** [comment]
I remeber now !!! this is the info popup : 
![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/1659842/d6226308-33af-4632-a5d2-62eef46d919b)

**Comment by sim51** [comment]
Done 

![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/13f88cef-28e7-49e3-ab8f-4709f857d1aa)
