### ISSUE TITLE
Add Sound

### ISSUE THREAD

**Issue by pierromond** [Universite-Gustave-Eiffel/lasso#23]
Simscene

**Comment by pierromond** [comment]
- generate 1000 sound files (get from Felix Gontier) and put in a repertory
- Label : recorder | generated/composition | auralized
- create a csv file PK  | Label | soundfile
- create a id_in_properties in index.json :  id_in_properties : "objective_id"

**Comment by paulgirard** [comment]
- add graphical representation of the sound length and current position

**Comment by sim51** [comment]
@pierromond can you provide some sound examples ?

**Comment by pierromond** [comment]
sent to you e-mail

**Comment by sim51** [comment]
merci !
