### ISSUE TITLE
Add photos for CartAsur

### ISSUE THREAD

**Issue by pierromond** [Universite-Gustave-Eiffel/lasso#24]
Objective : 
Show that the dataset have associated images.
How to aggregate the photo per point ? Where ?

**Comment by pierromond** [comment]
- Create a csv file avec PK |  PNG name | 
- Create a parameter in settings that say that there is a picture gallery
- show gallery as tooltip on the map
- create a id_in_properties in index.json :  id_in_properties : "objective_id"

**Comment by paulgirard** [comment]
- a la génération on associe les images d'un point à différents moments à la couche tmeps moyen

**Comment by sim51** [comment]
See https://github.com/Universite-Gustave-Eiffel/lasso/blob/dev/data/README.md#images for the documentation

![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/cc9cd0e4-0425-45a5-9d68-89437cba84ef)
