### ISSUE TITLE
add "about Lasso" on the first page

### ISSUE THREAD

**Issue by pierromond** [Universite-Gustave-Eiffel/lasso#26]

**Comment by sim51** [comment]
I just added the about page in the top  menu on the right.

![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/5f20e1d3-08fa-43cb-a8e1-42b16ff8d1b4)

The page title, description & content are directly taken from transifex for i18n, and the content can be a markdown.
Don't know if it's a good idea or not ... 

If not, I can load files `about.[lang].md` from somewhere. 
Ex: you can create them at the root of the project's data in the data folder, and then I load them in the app.

What do you prefer @pierromond  ?

**Comment by pierromond** [comment]
First thinking : maybe it should only be a small logo as "?".

About your general question about transifex : @nicolas-f explains me that the default language should be english and not codes like "page.about"

Finally about the question on the content, then I feel that :"The page title, description & content are directly taken from transifex for i18n, and the content can be a markdown." is a good idea. @nicolas-f could you just check my feeling ahaha :)

**Comment by sim51** [comment]
Is it better like that ? 
![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/1b4e260b-bec8-4855-b825-fac87f7f5eff)

**Comment by pierromond** [comment]
Yes :) nicer, simpler :)

**Comment by sim51** [comment]
... better 

For the content, I added an `about.en.md` file at the root of the `data` folder.
