### ISSUE TITLE
Fix cartridge

### ISSUE THREAD

**Issue by pierromond** [Universite-Gustave-Eiffel/lasso#27]
- Size of the circle, not color
- not number but slider above sound sources
- work on circumplex

**Comment by pierromond** [comment]
- Jauge for sound source value
- add button for reset time to average value
- Jauge for each emotion (one jauge by emotional variable)
- add separate black & white circumplex circle

**Comment by pierromond** [comment]
Manage empty values

**Comment by paulgirard** [comment]
- jauge dans le cercle existatn sous le symbol qui doit être détouré. La juge a aussi besoin d'une bordure.
- trouver une manière de permettre de supprimer la sélection du temps
- cercle dans animé/inanimé  agréable/désagréable
- signifier que les axes agréable/désagréable  sont des axes
- on passe en nuance de gris les éléments de légende qui ne sont pas représenté sur la carte choisie

**Comment by sim51** [comment]
![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/e63c56f3-2042-4764-82fb-dfc97dd3e36d)

**Comment by pierromond** [comment]
C'est bien visible plein, mais vide ça ira ? c'est dur de dire sans voir sur la plateforme. Mais dans l'idée globale c'est bien je crois, et proche de ce que l'on avait dit.

**Comment by sim51** [comment]
Voici en vide (fait à la main) :

![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/f0651265-7a4e-40e8-b2d7-a134abf76b85)

Je peux assombrir le gris pour que cela soit plus visible

**Comment by sim51** [comment]
Voici en vide (fait à la main) :

![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/f0651265-7a4e-40e8-b2d7-a134abf76b85)

Je peux assombrir le gris pour que cela soit plus visible

**Comment by sim51** [comment]
@pierromond  

Est-ce qu'on voit mieux que ce sont des axes avec les flèches  ?
Est-ce que tout passer en gris sauf l'axe correspondant à la variable courante c'est bon ?

![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/468dd227-664c-4eac-ac4c-e3e8e65e00d4)

**Comment by sim51** [comment]
Je suis pas convaincu par la suppression de la selection du temps que j'ai mis en place .
Le bouton "horloge" n'apparait uniquement lors qu'une selection est présente. 

![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/20bfe7a8-0a49-4661-b503-d1d59b744468)

Je propose deux alternatives : 

* supprimer la selection temporel lorsqu'on ferme le panneau
* garder l'icone "horloge" sur la carte, mais un click/survol affiche un selecteur de temps

**Comment by pierromond** [comment]
> Voici en vide (fait à la main) :
> 
> ![image](https://user-images.githubusercontent.com/231657/254885863-f0651265-7a4e-40e8-b2d7-a134abf76b85.png)
> 
> Je peux assombrir le gris pour que cela soit plus visible

Oui probablement assombrir le gris et le pense que le fond doit être le moins transparent possible, mais on pourra voir ces détails plus tard aussi.

**Comment by pierromond** [comment]
> @pierromond
> 
> Est-ce qu'on voit mieux que ce sont des axes avec les flèches ? Est-ce que tout passer en gris sauf l'axe correspondant à la variable courante c'est bon ?
> 
> ![image](https://user-images.githubusercontent.com/231657/254924331-468dd227-664c-4eac-ac4c-e3e8e65e00d4.png)

Oui, c'est mieux, je ne sais pas si je suis encore 100% convaincu, mais à la dernière réunion ça avait plus l'air de faire consensus :)Je suis trop déformé par ma manière de voir les choses en mode graph scientifique.
Soundscapy :
![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/1659842/828259b1-c0d1-4ce4-ac5b-2399ca9fb47f)

**Comment by pierromond** [comment]
> Je suis pas convaincu par la suppression de la selection du temps que j'ai mis en place . Le bouton "horloge" n'apparait uniquement lors qu'une selection est présente.
> 
> ![image](https://user-images.githubusercontent.com/231657/254941329-20bfe7a8-0a49-4661-b503-d1d59b744468.png)
> 
> Je propose deux alternatives :
> 
> * supprimer la selection temporel lorsqu'on ferme le panneau
> * garder l'icone "horloge" sur la carte, mais un click/survol affiche un selecteur de temps

Je n'arrive pas trop à comprendre ta question et les alternatives... désolé !

**Comment by sim51** [comment]
Pour le graph,  j'ai essayé de m'apporcher de ton visuel, juste en ajoutant une grille :

![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/09e4038e-3a42-4fa7-99e5-762483a77d35)

A propos de ma question, il ya en fait le ticket #11  qui me donne deja les réponses, je l'avais pas vu

**Comment by pierromond** [comment]
J'aime bien ça :)
