### ISSUE TITLE
Adapt Timeseries label to the language selected

### ISSUE THREAD

**Issue by paulgirard** [Universite-Gustave-Eiffel/lasso#8]

**Comment by sim51** [comment]
It's already the case, or do I miss something ?
Fr
![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/ec01708c-a498-4002-922a-dc2edced3e1f)

En
![image](https://github.com/Universite-Gustave-Eiffel/lasso/assets/231657/2f0d7d90-31c9-4349-81d1-67157add97d3)

**Comment by pierromond** [comment]
Oups, yes !
