### ISSUE TITLE
More flexible timeseries specification

### ISSUE THREAD

**Issue by paulgirard** [Universite-Gustave-Eiffel/lasso#9]
- [x] allow to define only some of the month/days/hours steps
For now the timeline will need all steps to be specified where some project could only need hours.
Workaround is to systematically define each steps and to produce one global step including every possible values for the non-needed steps, i.e. all twelwe months in a one "year" month step, all seven days in a "week" days steps...
- [x] allow over midnight hours range

**Comment by sim51** [comment]
There is no change in time specification,  it already handle all cases.

On the dataprep side, I changed the code to handle time range that crosses midnight.
On the application, the "time donut" is displayed even if there is no specification for "months" and/or "days".

What can be cool, is to displayed a "donut" for the finer time specification. 
For example : 
- if specification has only months, we should display a donut for the "seasons" 
- if specification has only months & days, we should display a donut for the "days"
